window.STATE_ASSISTANCE_DATA = [
  {
    "id": 1,
    "bureau": "ACN/CTR",
    "status": "Closed - pending awards",
    "title": "2026 CTR Non-Proliferation Programming",
    "awardId": "DFOP0017675",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-01-08",
    "closeDate": "2026-03-06",
    "expectedStart": "2027-01-01",
    "ceiling": 105000000,
    "expectedAwards": 50,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "VERY HIGH",
    "why": "Massive umbrella competition covering nonproliferation, advanced technology, research security, sanctions and related capacity building.",
    "source": "https://www.grants.gov/search-results-detail/361106",
    "grantsGovId": 361106,
    "opportunityUpdated": "Jan 08, 2026 01:37:59 PM EST"
  },
  {
    "id": 2,
    "bureau": "ACN/EXBS",
    "status": "Closed - pending award",
    "title": "Strengthening U.S. Advanced Technology Protection from Chinese Diversion in NEA, WHA, and EAP",
    "awardId": "DFOP0018150",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-05-18",
    "closeDate": "2026-07-20",
    "expectedStart": "2026-10-01",
    "ceiling": 4032350,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "VERY HIGH",
    "why": "Direct fit for export controls, FDI screening, legal/regulatory reform, compliance and diversion-risk analysis.",
    "source": "https://www.highergov.com/grant-opportunity/strengthening-u-s-advanced-technology-protection-from-chinese-diversion-in-nea-362459/"
  },
  {
    "id": 3,
    "bureau": "ACN/EXBS",
    "status": "Closed - pending award",
    "title": "EXBS Legal & Regulatory Support",
    "awardId": "DFOP0018151",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-06-05",
    "closeDate": "2026-07-20",
    "expectedStart": "",
    "ceiling": 2441589,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "VERY HIGH",
    "why": "Probably the cleanest direct fit for Lexpat legal/regulatory, export-control and compliance support.",
    "source": "https://www.grants.gov/search-results-detail/362695",
    "grantsGovId": 362695,
    "opportunityUpdated": "Jun 05, 2026 11:34:26 AM EDT"
  },
  {
    "id": 4,
    "bureau": "ACN/EXBS",
    "status": "Closed - pending award",
    "title": "Data Analytics & AI to Counter Global Diversion",
    "awardId": "DFOP0018157",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-07-16",
    "closeDate": "2026-08-21",
    "expectedStart": "",
    "ceiling": 5901000,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "VERY HIGH",
    "why": "Combines export controls, data analytics, inspections, industry outreach and legal/compliance workstreams.",
    "source": "https://www.grants.gov/search-results-detail/363221",
    "grantsGovId": 363221,
    "opportunityUpdated": "Jul 16, 2026 02:56:41 PM EDT"
  },
  {
    "id": 5,
    "bureau": "ACN/EXBS",
    "status": "Closed - pending award",
    "title": "Protecting Critical Mineral Supply Chains / export controls and screening",
    "awardId": "DFOP0018149",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-06-25",
    "closeDate": "2026-07-20",
    "expectedStart": "",
    "ceiling": 5409250,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "HIGH",
    "why": "Export controls, customs screening, investment screening and critical-minerals supply-chain security.",
    "source": "https://www.grants.gov/search-results-detail/362963",
    "grantsGovId": 362963,
    "opportunityUpdated": "Jun 25, 2026 06:17:19 AM EDT"
  },
  {
    "id": 6,
    "bureau": "ACN/NDF",
    "status": "Closed - pending awards",
    "title": "Mitigating Proliferation Risks Posed by AI-Enabled Molecular Models and Leveraging Nonproliferation Opportunities",
    "awardId": "DFOP0018449",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-06-29",
    "closeDate": "2026-07-21",
    "expectedStart": "",
    "ceiling": 4000000,
    "expectedAwards": 3,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "MEDIUM-HIGH",
    "why": "Potential legal/policy, governance, responsible technology and nonproliferation advisory role.",
    "source": "https://www.grants.gov/search-results-detail/362991",
    "grantsGovId": 362991,
    "opportunityUpdated": "Jun 29, 2026 11:04:52 AM EDT"
  },
  {
    "id": 7,
    "bureau": "CT",
    "status": "AWARDED",
    "title": "Terrorist asset identification, freezing and seizure capacity building",
    "awardId": "SAQMMA26CA0035",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-06-01",
    "closeDate": "",
    "expectedStart": "2026-06-01",
    "ceiling": 4933399,
    "expectedAwards": 1,
    "winner": "Bancroft Global Development",
    "awardAmount": 4933399,
    "relevance": "VERY HIGH",
    "why": "Near-perfect fit for AML/CFT, FIUs, law enforcement, prosecutors, judiciary and terrorist-finance work.",
    "source": "https://www.usaspending.gov/award/ASST_NON_SAQMMA26CA0035_019/",
    "officialRecipient": "BANCROFT GLOBAL DEVELOPMENT",
    "awardEnd": "2027-05-31",
    "usaSpendingLastModified": "2026-06-05 17:56:58"
  },
  {
    "id": 8,
    "bureau": "CT",
    "status": "Closed - pending award",
    "title": "Countering Foreign Terrorist Organization Use of Illicit Mining",
    "awardId": "DFOP0018686",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-07-06",
    "closeDate": "2026-07-15",
    "expectedStart": "2026-09-30",
    "ceiling": 4933399,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "VERY HIGH",
    "why": "Illicit finance, TCO/FTO networks, regulators, prosecutors and investigations align strongly with Lexpat.",
    "source": "https://www.grants.gov/search-results-detail/363068",
    "grantsGovId": 363068,
    "opportunityUpdated": "Jul 06, 2026 09:48:40 AM EDT"
  },
  {
    "id": 9,
    "bureau": "CT",
    "status": "Closed - pending award",
    "title": "Countering Terrorist Recruitment Online",
    "awardId": "DFOP0018502",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-06-22",
    "closeDate": "2026-07-27",
    "expectedStart": "2026-09-30",
    "ceiling": 4933399,
    "expectedAwards": "1+",
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "HIGH",
    "why": "Investigations, legal frameworks, law-enforcement capacity and emerging-tech policy components may fit.",
    "source": "https://www.grants.gov/search-results-detail/362904",
    "grantsGovId": 362904,
    "opportunityUpdated": "Jun 22, 2026 12:53:47 PM EDT"
  },
  {
    "id": 10,
    "bureau": "CT",
    "status": "Closed - pending awards",
    "title": "Countering Terrorist Recruitment of Central Asian Foreign Workers",
    "awardId": "DFOP0018082",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-04-01",
    "closeDate": "2026-06-09",
    "expectedStart": "",
    "ceiling": 986679,
    "expectedAwards": "Up to 2",
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "MEDIUM-HIGH",
    "why": "Counterterrorism programming and prevention; possible legal/policy and training subcontract role.",
    "source": "https://files.simpler.grants.gov/opportunities/aa2b27e1-75e8-499e-acb0-efd91bbf32ae/attachments/9bcd21e8-faa5-438c-9eac-f5d8a24c6471/FP_-_NOFO_Countering_Terrorist_Recruitment_of_Central_Asian_Foreign_Workers.pdf"
  },
  {
    "id": 11,
    "bureau": "CT",
    "status": "Closed - pending award",
    "title": "Preventing Iranian Proxy and ISIS Activities Along Iraq’s Western Border",
    "awardId": "DFOP0018090",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-04-29",
    "closeDate": "2026-06-08",
    "expectedStart": "2026-09-30",
    "ceiling": 6808090,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "VERY HIGH",
    "why": "Direct overlap with Lexpat Iraq, Iran-aligned militia, CT, investigations and institutional-capacity work.",
    "source": "https://www.grants.gov/search-results-detail/362131",
    "grantsGovId": 362131,
    "opportunityUpdated": "Apr 29, 2026 02:18:50 PM EDT"
  },
  {
    "id": 12,
    "bureau": "CT",
    "status": "Closed - pending award",
    "title": "Regional Explosive Ordnance Disposal Operations in the Near East",
    "awardId": "DFOP0018683",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-07-17",
    "closeDate": "2026-07-20",
    "expectedStart": "",
    "ceiling": 3946719,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "MEDIUM",
    "why": "Security-sector capacity and regional implementation; legal/compliance support possible but less core.",
    "source": "https://www.grants.gov/search-results-detail/363231",
    "grantsGovId": 363231,
    "opportunityUpdated": "Jul 17, 2026 02:59:05 PM EDT"
  },
  {
    "id": 13,
    "bureau": "DRL",
    "status": "Closed - pending award",
    "title": "Global Documentation for Accountability Initiative",
    "awardId": "DFOP0019396",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-07-16",
    "closeDate": "2026-08-17",
    "expectedStart": "",
    "ceiling": 4932500,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "VERY HIGH",
    "why": "Core Lexpat lane: evidence, accountability, sanctions, visa restrictions, investigations and legal analysis.",
    "source": "https://www.grants.gov/search-results-detail/363211",
    "grantsGovId": 363211,
    "opportunityUpdated": "Jul 16, 2026 11:10:43 AM EDT"
  },
  {
    "id": 14,
    "bureau": "DRL",
    "status": "Closed - pending award",
    "title": "Emergency Assistance for Fundamental Freedom Defenders",
    "awardId": "DFOP0019749",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-09-01",
    "closeDate": "2026-09-08",
    "expectedStart": "",
    "ceiling": 4932500,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "HIGH",
    "why": "Human-rights protection and emergency mechanisms; possible legal/protection/risk-advisory role.",
    "source": "https://www.grants.gov/search-results-detail/363780",
    "grantsGovId": 363780,
    "opportunityUpdated": "Sep 01, 2026 03:44:04 PM EDT"
  },
  {
    "id": 15,
    "bureau": "DRL",
    "status": "Closed - pending award",
    "title": "Global Rapid Response Fund for Advancing Fundamental Freedoms",
    "awardId": "DFOP0019705",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-08-18",
    "closeDate": "2026-08-31",
    "expectedStart": "",
    "ceiling": 9569050,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "HIGH",
    "why": "Rapid response, local partners, democracy and human-rights programming; possible specialist teaming role.",
    "source": "https://www.grants.gov/search-results-detail/363646",
    "grantsGovId": 363646,
    "opportunityUpdated": "Aug 18, 2026 02:34:51 PM EDT"
  },
  {
    "id": 16,
    "bureau": "DRL",
    "status": "Closed - pending award",
    "title": "Promoting Sovereignty and Rule of Law in Europe",
    "awardId": "DFOP0019631",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-08-14",
    "closeDate": "2026-08-31",
    "expectedStart": "",
    "ceiling": 2960039,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "VERY HIGH",
    "why": "Rule of law, policy and legal analysis are central Lexpat capabilities.",
    "source": "https://www.grants.gov/search-results-detail/363595",
    "grantsGovId": 363595,
    "opportunityUpdated": "Aug 14, 2026 09:24:52 AM EDT"
  },
  {
    "id": 17,
    "bureau": "DRL",
    "status": "Closed - pending award",
    "title": "TNR: academic/judicial tools to identify, document and respond to transnational repression",
    "awardId": "DFOP0019436",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-07-21",
    "closeDate": "2026-08-20",
    "expectedStart": "",
    "ceiling": 1973359,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "VERY HIGH",
    "why": "Judicial, documentation and legal-accountability work aligns closely with Lexpat.",
    "source": "https://www.grants.gov/search-results-detail/363259",
    "grantsGovId": 363259,
    "opportunityUpdated": "Jul 21, 2026 10:05:42 AM EDT"
  },
  {
    "id": 18,
    "bureau": "DRL",
    "status": "Closed - pending award",
    "title": "TNR: investigate infiltration of diaspora communities by faith-based or quasi-government organizations",
    "awardId": "DFOP0019655",
    "instrument": "Grant",
    "postedDate": "2026-08-04",
    "closeDate": "2026-08-10",
    "expectedStart": "",
    "ceiling": 986679,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "HIGH",
    "why": "Investigations, evidence development and policy recommendations align with Lexpat capabilities.",
    "source": "https://www.grants.gov/search-results-detail/363465",
    "grantsGovId": 363465,
    "opportunityUpdated": "Aug 04, 2026 05:00:47 PM EDT"
  },
  {
    "id": 19,
    "bureau": "DRL",
    "status": "Closed - pending award",
    "title": "Track 2.0 Peacebuilding Rapid Response Mechanism",
    "awardId": "DFOP0019287",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-07-15",
    "closeDate": "2026-08-13",
    "expectedStart": "",
    "ceiling": 1973359,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "MEDIUM-HIGH",
    "why": "Conflict/peacebuilding and convening; teaming fit strongest if legal/accountability elements are needed.",
    "source": "https://www.grants.gov/search-results-detail/363202",
    "grantsGovId": 363202,
    "opportunityUpdated": "Jul 15, 2026 04:45:01 PM EDT"
  },
  {
    "id": 20,
    "bureau": "INL",
    "status": "Closed - pending awards",
    "title": "Securing Convictions from Vetted and Special Unit Operations - Mexico",
    "awardId": "OFOP0002421",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-03-02",
    "closeDate": "2026-03-20",
    "expectedStart": "2026-04-01",
    "ceiling": 1500000,
    "expectedAwards": 4,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "VERY HIGH",
    "why": "Prosecution, investigations, case-building and criminal justice capacity are direct fits.",
    "source": "https://www.grants.gov/search-results-detail/361388",
    "grantsGovId": 361388,
    "opportunityUpdated": "Mar 02, 2026 03:32:43 PM EST"
  },
  {
    "id": 21,
    "bureau": "INL",
    "status": "Closed - pending award",
    "title": "Combating TCOs through Data-Driven Analysis and Customized Investigative Mentoring - Bosnia and Herzegovina",
    "awardId": "OFOP0003000",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-06-15",
    "closeDate": "2026-08-17",
    "expectedStart": "",
    "ceiling": 650000,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "VERY HIGH",
    "why": "Illicit finance, corruption, prosecutors and investigative mentoring align almost exactly with Lexpat.",
    "source": "https://www.grants.gov/search-results-detail/362805",
    "grantsGovId": 362805,
    "opportunityUpdated": "Jun 15, 2026 11:03:52 AM EDT"
  },
  {
    "id": 22,
    "bureau": "INL",
    "status": "Closed - pending award",
    "title": "Technical Assistance to Combat TCOs and Prevent FTO Operations in SCC Partner Countries",
    "awardId": "DFOP0019393",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-07-16",
    "closeDate": "2026-08-17",
    "expectedStart": "",
    "ceiling": 500000,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "HIGH",
    "why": "Law enforcement, criminal justice and TCO/FTO technical assistance align with Lexpat.",
    "source": "https://www.grants.gov/search-results-detail/363218",
    "grantsGovId": 363218,
    "opportunityUpdated": "Jul 16, 2026 12:54:54 PM EDT"
  },
  {
    "id": 23,
    "bureau": "PM/WRA",
    "status": "AWARDED",
    "title": "Humanitarian demining and UXO clearance - Cambodia",
    "awardId": "SPMWRA26CA0004",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-02-01",
    "closeDate": "",
    "expectedStart": "2026-02-01",
    "ceiling": 5000000,
    "expectedAwards": 1,
    "winner": "Norsk Folkehjelp",
    "awardAmount": 5000000,
    "relevance": "MEDIUM",
    "why": "Useful partner ecosystem for security-sector and conventional weapons work; less direct than legal/AML lanes.",
    "source": "https://www.usaspending.gov/award/ASST_NON_SPMWRA26CA0004_019/",
    "officialRecipient": "NORSK FOLKEHJELP",
    "awardEnd": "2027-07-31",
    "usaSpendingLastModified": "2026-02-09 18:56:26"
  },
  {
    "id": 24,
    "bureau": "PM/WRA",
    "status": "AWARDED",
    "title": "Humanitarian demining / risk education - Colombia",
    "awardId": "SPMWRA26GR0006",
    "instrument": "Project Grant",
    "postedDate": "2026-06-01",
    "closeDate": "",
    "expectedStart": "2026-06-01",
    "ceiling": 5000000,
    "expectedAwards": 1,
    "winner": "Asociacion Campana Colombiana Contra Minas (CCCM)",
    "awardAmount": 5000000,
    "relevance": "MEDIUM",
    "why": "Relevant to Colombia and security-sector networks; potential policy/legal or monitoring support.",
    "source": "https://www.usaspending.gov/award/ASST_NON_SPMWRA26GR0006_019/",
    "officialRecipient": "ASOCIACION CAMPANA COLOMBIANA CONTRA MINAS CCCM",
    "awardEnd": "2027-05-31",
    "usaSpendingLastModified": "2026-05-22 22:19:20"
  },
  {
    "id": 25,
    "bureau": "ECA",
    "status": "AWARDED",
    "title": "FY 2026 International Visitor Leadership Program - NPA support",
    "awardId": "SECAGD26CA0013",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-03-26",
    "closeDate": "",
    "expectedStart": "2026-03-26",
    "ceiling": 2783981,
    "expectedAwards": 1,
    "winner": "CRDF Global",
    "awardAmount": 2783981,
    "relevance": "HIGH",
    "why": "Shows CRDF remains an active 2026 State assistance winner and a live teaming target.",
    "source": "https://www.usaspending.gov/award/ASST_NON_SECAGD26CA0013_019/",
    "officialRecipient": "U.S. CIVILIAN RESEARCH AND DEVELOPMENT FOUNDATION",
    "awardEnd": "2029-01-01",
    "usaSpendingLastModified": "2026-08-21 18:37:48"
  },
  {
    "id": 26,
    "bureau": "ECA",
    "status": "AWARDED",
    "title": "FY 2026 International Visitor Leadership Program - NPA support",
    "awardId": "SECAGD26CA0015",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-03-28",
    "closeDate": "",
    "expectedStart": "2026-03-28",
    "ceiling": 2512833,
    "expectedAwards": 1,
    "winner": "FHI 360",
    "awardAmount": 4885504,
    "relevance": "MEDIUM",
    "why": "Large implementer with active State assistance portfolio; useful as a teaming target for specialist work.",
    "source": "https://www.usaspending.gov/award/ASST_NON_SECAGD26CA0015_019/",
    "officialRecipient": "FAMILY HEALTH INTERNATIONAL",
    "awardEnd": "2029-01-01",
    "usaSpendingLastModified": "2026-09-10 18:45:09"
  },
  {
    "id": 27,
    "bureau": "ECA",
    "status": "AWARDED",
    "title": "FY 2026 International Visitor Leadership Program",
    "awardId": "SECAGD26CA0014",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-03-31",
    "closeDate": "",
    "expectedStart": "2026-03-31",
    "ceiling": 1880000,
    "expectedAwards": 1,
    "winner": "Cultural Vistas",
    "awardAmount": 3962249,
    "relevance": "LOW-MEDIUM",
    "why": "Active ECA implementer; less direct capability overlap but potential niche legal/policy programming.",
    "source": "https://www.usaspending.gov/award/ASST_NON_SECAGD26CA0014_019/",
    "officialRecipient": "CULTURAL VISTAS, INC.",
    "awardEnd": "2029-01-01",
    "usaSpendingLastModified": "2026-09-10 18:45:09"
  },
  {
    "id": 28,
    "bureau": "ECA",
    "status": "AWARDED",
    "title": "FY 2026 Fulbright Specialist Program",
    "awardId": "SECAGD26CA0007",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-01-09",
    "closeDate": "",
    "expectedStart": "2026-01-09",
    "ceiling": 1445637,
    "expectedAwards": 1,
    "winner": "World Learning",
    "awardAmount": 4335000,
    "relevance": "MEDIUM",
    "why": "Active international implementer with broad State footprint; potential specialist teaming partner.",
    "source": "https://www.usaspending.gov/award/ASST_NON_SECAGD26CA0007_019/",
    "officialRecipient": "WORLD LEARNING INC.",
    "awardEnd": "2030-10-01",
    "usaSpendingLastModified": "2026-06-22 17:02:03"
  },
  {
    "id": 29,
    "bureau": "ECA",
    "status": "AWARDED",
    "title": "FY 2026 Fulbright Teacher Exchanges",
    "awardId": "SECAGD26CA0005",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-01-23",
    "closeDate": "",
    "expectedStart": "2026-01-23",
    "ceiling": 600348,
    "expectedAwards": 1,
    "winner": "IREX",
    "awardAmount": 6720000,
    "relevance": "MEDIUM",
    "why": "IREX is an active State grantee and potential partner for governance, research-security or institutional work.",
    "source": "https://www.usaspending.gov/award/ASST_NON_SECAGD26CA0005_019/",
    "officialRecipient": "INTERNATIONAL RESEARCH AND EXCHANGES BOARD INC.",
    "awardEnd": "2030-05-01",
    "usaSpendingLastModified": "2026-05-22 22:19:20"
  },
  {
    "id": 30,
    "bureau": "ECA",
    "status": "Archived - award not verified",
    "title": "FY 2026 Community Solutions Program",
    "awardId": "DFOP0018816",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-06-24",
    "closeDate": "2026-07-23",
    "expectedStart": "",
    "ceiling": 3000000,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "LOW-MEDIUM",
    "why": "Less direct fit, but useful for tracking active international implementation organizations.",
    "source": "https://www.grants.gov/search-results-detail/362944",
    "grantsGovId": 362944,
    "opportunityUpdated": "Jun 24, 2026 12:52:24 PM EDT"
  },
  {
    "id": 31,
    "bureau": "ECA",
    "status": "Archived - award not verified",
    "title": "FY 2026 Strengthening Talent, Research, Innovation and Vital Engagement (STRIVE)",
    "awardId": "DFOP0018335",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-05-12",
    "closeDate": "2026-06-10",
    "expectedStart": "",
    "ceiling": 2000000,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "MEDIUM",
    "why": "Research/innovation and institutional partnerships could overlap with nonproliferation and tech-security work.",
    "source": "https://www.grants.gov/search-results-detail/362356",
    "grantsGovId": 362356,
    "opportunityUpdated": "May 12, 2026 09:13:25 AM EDT"
  },
  {
    "id": 32,
    "bureau": "ECA",
    "status": "Archived - award not verified",
    "title": "FY 2026 Community Engagement Exchange",
    "awardId": "DFOP0018606",
    "instrument": "Cooperative Agreement",
    "postedDate": "2026-06-10",
    "closeDate": "2026-07-09",
    "expectedStart": "",
    "ceiling": 1000000,
    "expectedAwards": 1,
    "winner": "TBD",
    "awardAmount": null,
    "relevance": "LOW-MEDIUM",
    "why": "Useful mainly to identify active ECA implementers and potential broad teaming partners.",
    "source": "https://www.grants.gov/search-results-detail/362751",
    "grantsGovId": 362751,
    "opportunityUpdated": "Jun 10, 2026 12:25:27 PM EDT"
  }
];

window.STATE_ASSISTANCE_META = {
  "asOf": "September 24, 2026",
  "lastChecked": "2026-09-24",
  "sources": [
    "Grants.gov",
    "USAspending.gov"
  ]
};
